package gerber

import (
	"fmt"
	"math"
	"sort"
	"strings"

	"github.com/mentasystems/fragua/internal/core"
)

// writeIPCD356 emits an IPC-D-356A bare-board netlist.
//
// Record layout matches KiCad's export_d356.cpp / gerbv (the format CAM
// tools actually parse), not a invented lookalike:
//
//	C  comment
//	P  JOB / VER / CODE 00 / UNITS CUST 0 / arrayDim N
//	327  SMD pad     (primary surface-mount test point)
//	317  through-hole via or PTH pad
//	307  blind/buried (unused here — we have through vias only)
//	999  end of file
//
// Feature record (KiCad fprintf, 1-based columns):
//
//	1–3    record type
//	4–17   net name (14 chars, left)
//	18     space
//	19–24  refdes (6)
//	25     '-' if pin present, else space
//	26–29  pin (4)
//	30     'M' midpoint (via / unnamed copper) or space (component pin)
//	then   DddddP  plated hole (decimils) or a single space if SMD
//	then   AaalX±xxxxxxY±yyyyyyXwwwwYhhhhRrrr
//	then   Ss
//
// P UNITS CUST 0 = 0.0001 inch (decimil) and degrees. CUST 1 (mm) is
// ignored by several CAM tools, so we stay on CUST 0.
func writeIPCD356(board *core.Board, job string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "C  IPC-D-356A Bare Board Electrical Test Information\n")
	fmt.Fprintf(&b, "C  Generated by Fragua %s\n", core.Version)
	fmt.Fprintf(&b, "C  Job: %s\n", job)
	fmt.Fprintf(&b, "C  Origin: board lower-left (X right, Y up)\n")
	fmt.Fprintf(&b, "C  Units: CUST 0 = 0.0001 inch (decimil), degrees\n")
	fmt.Fprintf(&b, "P  JOB   %s\n", sanitize(job))
	fmt.Fprintf(&b, "P  VER   IPC-D-356A\n")
	fmt.Fprintf(&b, "P  CODE 00\n")
	fmt.Fprintf(&b, "P  UNITS CUST 0\n")
	fmt.Fprintf(&b, "P  arrayDim N\n")

	type rec struct {
		smd      bool
		hole     bool
		net      string
		refdes   string
		pin      string
		midpoint bool
		drillMM  float64
		access   int
		xMM, yMM float64
		wMM, hMM float64
		rot      int
		mask     int
	}
	var recs []rec
	nCu := board.StackupOrDefault().CopperCount()
	if nCu < 2 {
		nCu = 2
	}

	for _, fp := range footprintsInOrder(board) {
		rot := int(math.Round(math.Mod(fp.Rotation, 360)))
		if rot < 0 {
			rot += 360
		}
		if rot >= 1000 {
			rot = 999
		}
		for i := range fp.Pads {
			pad := &fp.Pads[i]
			net := "N/C"
			if pad.Net != nil && *pad.Net != "" {
				net = *pad.Net
			}
			c := core.PadWorldCenter(fp, pad)
			pw, ph := core.PadWorldSize(fp, pad)
			r := rec{
				net:    net,
				refdes: fp.Reference,
				pin:    pad.Number,
				xMM:    c.X.ToMM(),
				yMM:    c.Y.ToMM(),
				wMM:    pw.ToMM(),
				hMM:    ph.ToMM(),
				rot:    rot,
				mask:   0,
			}
			if pad.Drill != nil {
				r.smd = false
				r.hole = true
				r.drillMM = pad.Drill.ToMM()
				r.access = 0 // through-hole
			} else {
				r.smd = true
				if pad.Layer.IsTop() {
					r.access = 1
				} else {
					r.access = nCu
				}
			}
			recs = append(recs, r)
		}
	}
	for i := range board.Vias {
		v := &board.Vias[i]
		net := v.Net
		if net == "" {
			net = "N/C"
		}
		recs = append(recs, rec{
			smd:      false,
			hole:     true,
			net:      net,
			refdes:   "VIA",
			midpoint: true,
			drillMM:  v.Drill.ToMM(),
			access:   0,
			xMM:      v.Position.X.ToMM(),
			yMM:      v.Position.Y.ToMM(),
			wMM:      v.Diameter.ToMM(),
			hMM:      v.Diameter.ToMM(),
			mask:     0,
		})
	}

	sort.SliceStable(recs, func(i, j int) bool {
		if recs[i].net != recs[j].net {
			return recs[i].net < recs[j].net
		}
		if recs[i].refdes != recs[j].refdes {
			return recs[i].refdes < recs[j].refdes
		}
		return recs[i].pin < recs[j].pin
	})

	for _, r := range recs {
		rk := 327
		if !r.smd {
			rk = 317
		}
		net := r.net
		if len(net) > 14 {
			net = net[:14]
		}
		ref := r.refdes
		if len(ref) > 6 {
			ref = ref[:6]
		}
		pin := r.pin
		if len(pin) > 4 {
			pin = pin[:4]
		}
		pinSep := byte(' ')
		if pin != "" {
			pinSep = '-'
		}
		mid := byte(' ')
		if r.midpoint {
			mid = 'M'
		}
		fmt.Fprintf(&b, "%03d%-14.14s %-6.6s%c%-4.4s%c",
			rk, net, ref, pinSep, pin, mid)
		if r.hole {
			fmt.Fprintf(&b, "D%04dP", mmToDecimil(r.drillMM, 9999))
		} else {
			b.WriteByte(' ')
		}
		fmt.Fprintf(&b, "A%02dX%+07dY%+07dX%04dY%04dR%03dS%d\n",
			r.access,
			mmToDecimil(r.xMM, 999999),
			mmToDecimil(r.yMM, 999999),
			mmToDecimil(r.wMM, 9999),
			mmToDecimil(r.hMM, 9999),
			r.rot,
			r.mask,
		)
	}
	b.WriteString("999\n")
	return b.String()
}

// mmToDecimil converts millimetres to IPC-D-356 CUST 0 units (0.0001 inch).
func mmToDecimil(mm float64, clamp int) int {
	v := int(math.Round(mm * 10000.0 / 25.4))
	if v > clamp {
		return clamp
	}
	if v < -clamp {
		return -clamp
	}
	return v
}
